# Generated by Django 4.2.8 on 2023-12-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_timestamp_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
